# Generated by Django 5.0.3 on 2026-04-27 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "module",
                    models.CharField(
                        blank=True,
                        help_text="ERP module this permission belongs to (accounts, finance, sales, …)",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "db_table": "erp_permissions",
                "ordering": ["module", "code"],
            },
        ),
        migrations.AlterField(
            model_name="company",
            name="max_users",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("finance", "Finance"),
                    ("sales", "Sales"),
                    ("hr_manager", "HR Manager"),
                    ("auditor", "Auditor"),
                    ("staff", "Staff"),
                ],
                default="staff",
                max_length=20,
                verbose_name="role",
            ),
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("manager", "Manager"),
                            ("finance", "Finance"),
                            ("sales", "Sales"),
                            ("hr_manager", "HR Manager"),
                            ("auditor", "Auditor"),
                            ("staff", "Staff"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="accounts.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Permission",
                "verbose_name_plural": "Role Permissions",
                "db_table": "role_permissions",
                "unique_together": {("role", "permission")},
            },
        ),
        migrations.CreateModel(
            name="UserPermissionOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "granted",
                    models.BooleanField(
                        default=True,
                        help_text="True = grant this permission to the user; False = revoke it even if their role has it",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_overrides",
                        to="accounts.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Permission Override",
                "verbose_name_plural": "User Permission Overrides",
                "db_table": "user_permission_overrides",
                "unique_together": {("user", "permission")},
            },
        ),
    ]
